import type { Metadata } from "next";
import {
    Roboto,
    Diplomata,
    Notable,
    Atkinson_Hyperlegible_Mono,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const getRoboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const getDiplomata = Diplomata({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400"],
});

const getNotable = Notable({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400"],
});

const getAtkinson = Atkinson_Hyperlegible_Mono({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "El Bodegón del Náutico",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
